### ISSUE TITLE
Небольшая недоработка ♂

### ISSUE THREAD

**Issue by dodokek** [vitosotdihaet/chang-e-1-simulation#1]
Почему в вашей игре нельзя врезаться ракетой в планету, чтобы один из этих объектов взорвался и при этом были супер дупер крутые спецэффекты?

**Comment by vitosotdihaet** [comment]
Извините, данная ветка проекта нацелена не на это. Можете отправить подобную проблему в ветку ```main``` и я обязательно реализую эту функцию!
